# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SNAPSHOT_ARTIFACTS: "/tmp/SNAPSHOTS"
  DERIVEDDATA_PATH: "/tmp/DerivedData"
  DEVELOPER_DIR: "/Applications/Xcode_14.3.1.app"

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ${{ env.DERIVEDDATA_PATH }}/SourcePackages/checkouts/
        key: ${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}

    - run: set -o pipefail && xcodebuild test -project Demo/Demo.xcodeproj -scheme Demo -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' -enableCodeCoverage YES -derivedDataPath ${{ env.DERIVEDDATA_PATH }} | xcpretty
    - uses: michaelhenry/swifty-code-coverage@v1.0.1
      with:
        build-path: ${{ env.DERIVEDDATA_PATH }}
        target: Demo.app
        is-spm: false
        ignore-filename-regex: 'Demo|ViewController|DerivedData|.libs|AnyDiffableDataSource'

    - name: Upload to Codecov
      run: |
        bash <(curl https://codecov.io/bash) -f "coverage/*.info"
      shell: bash
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive Failing UI Snapshots
      uses: actions/upload-artifact@v4.3.3
      if: failure()
      with:
        name: failing-ui-snapshots-artifact
        path: |
          ${{ env.SNAPSHOT_ARTIFACTS }}
